"""Initial schema

Revision ID: b2e4a76b9856
Revises: 
Create Date: 2026-06-06 00:54:29.723199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2e4a76b9856'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'operator', 'viewer')", name='check_user_role'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('dropdown_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('option_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.CheckConstraint("option_type IN ('project_sector', 'cost_type')", name='check_dropdown_option_type'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('option_type', 'name', name='uq_dropdown_option_type_name')
    )
    with op.batch_alter_table('dropdown_option', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dropdown_option_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_dropdown_option_option_type'), ['option_type'], unique=False)

    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('firm_name', sa.String(length=200), nullable=True),
    sa.Column('tender_id', sa.String(length=100), nullable=True),
    sa.Column('noa_date', sa.Date(), nullable=True),
    sa.Column('work_order_year', sa.String(length=50), nullable=True),
    sa.Column('contract_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('additional_details', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_void', sa.Boolean(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('Running', 'Completed', 'On Hold')", name='check_project_status'),
    sa.CheckConstraint('contract_price >= 0', name='check_positive_contract_price'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_name', 'tender_id', name='uq_project_tender')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_is_void'), ['is_void'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_sector'), ['sector'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_tender_id'), ['tender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_work_order_year'), ['work_order_year'], unique=False)

    op.create_table('project_deleted_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('deleted_by', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('project_snapshot', sa.Text(), nullable=False),
    sa.Column('costs_voided_count', sa.Integer(), nullable=True),
    sa.Column('void_reason', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['deleted_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_deleted_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_deleted_log_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_deleted_log_deleted_by'), ['deleted_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_deleted_log_project_id'), ['project_id'], unique=False)

    op.create_table('cost_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('cost_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('unit_rate', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=True),
    sa.Column('is_void', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cost_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cost_entry_cost_type'), ['cost_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_entry_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_entry_is_void'), ['is_void'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_entry_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_entry_user_id'), ['user_id'], unique=False)

    op.create_table('deleted_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cost_id', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('project_name_snapshot', sa.String(length=200), nullable=False),
    sa.Column('data_snapshot', sa.Text(), nullable=False),
    sa.Column('void_reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deleted_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deleted_log_cost_id'), ['cost_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deleted_log_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_deleted_log_deleted_by'), ['deleted_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_deleted_log_project_id'), ['project_id'], unique=False)

    op.create_table('edit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cost_id', sa.Integer(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('project_name_snapshot', sa.String(length=200), nullable=True),
    sa.Column('before_snapshot', sa.Text(), nullable=False),
    sa.Column('after_snapshot', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('edit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edit_log_changed_at'), ['changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_edit_log_changed_by'), ['changed_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_edit_log_cost_id'), ['cost_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edit_log_project_id'), ['project_id'], unique=False)

    op.create_table('project_edit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('project_name_snapshot', sa.String(length=200), nullable=True),
    sa.Column('before_snapshot', sa.Text(), nullable=False),
    sa.Column('after_snapshot', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_edit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_edit_log_changed_at'), ['changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_edit_log_changed_by'), ['changed_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_edit_log_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_edit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_edit_log_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_edit_log_changed_by'))
        batch_op.drop_index(batch_op.f('ix_project_edit_log_changed_at'))

    op.drop_table('project_edit_log')
    with op.batch_alter_table('edit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edit_log_project_id'))
        batch_op.drop_index(batch_op.f('ix_edit_log_cost_id'))
        batch_op.drop_index(batch_op.f('ix_edit_log_changed_by'))
        batch_op.drop_index(batch_op.f('ix_edit_log_changed_at'))

    op.drop_table('edit_log')
    with op.batch_alter_table('deleted_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deleted_log_project_id'))
        batch_op.drop_index(batch_op.f('ix_deleted_log_deleted_by'))
        batch_op.drop_index(batch_op.f('ix_deleted_log_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_deleted_log_cost_id'))

    op.drop_table('deleted_log')
    with op.batch_alter_table('cost_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cost_entry_user_id'))
        batch_op.drop_index(batch_op.f('ix_cost_entry_project_id'))
        batch_op.drop_index(batch_op.f('ix_cost_entry_is_void'))
        batch_op.drop_index(batch_op.f('ix_cost_entry_date'))
        batch_op.drop_index(batch_op.f('ix_cost_entry_cost_type'))

    op.drop_table('cost_entry')
    with op.batch_alter_table('project_deleted_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_deleted_log_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_deleted_log_deleted_by'))
        batch_op.drop_index(batch_op.f('ix_project_deleted_log_deleted_at'))

    op.drop_table('project_deleted_log')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_work_order_year'))
        batch_op.drop_index(batch_op.f('ix_project_user_id'))
        batch_op.drop_index(batch_op.f('ix_project_tender_id'))
        batch_op.drop_index(batch_op.f('ix_project_status'))
        batch_op.drop_index(batch_op.f('ix_project_sector'))
        batch_op.drop_index(batch_op.f('ix_project_is_void'))

    op.drop_table('project')
    with op.batch_alter_table('dropdown_option', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dropdown_option_option_type'))
        batch_op.drop_index(batch_op.f('ix_dropdown_option_created_by'))

    op.drop_table('dropdown_option')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    # ### end Alembic commands ###
