
from io import BytesIO
from datetime import datetime, timezone, timedelta
from pathlib import Path
from xml.sax.saxutils import escape

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, KeepTogether, PageBreak
)

from decimal import InvalidOperation

from app.modules.construction.utils.money import format_money, percent_used, to_money, ZERO
from app.modules.construction.utils.report_palette import (
    ACCENT_HEX,
    BORDER_GREY_HEX,
    BOX_GREY_HEX,
    DARK_GREY_HEX,
    FOOTER_FILL_HEX,
    FOOTER_LINE_HEX,
    INK_HEX,
    LEDGER_DIVIDER_HEX,
    LIGHT_GREY_HEX,
    MID_GREY_HEX,
    ROW_ALT_HEX,
    SCOPE_GRID_HEX,
    TAGLINE_HEX,
    TOTAL_FILL_HEX,
    css_hex,
)

# ── Brand colours ─────────────────────────────────────────────────────────────
NAVY       = colors.HexColor(css_hex(INK_HEX))
RED        = colors.HexColor(css_hex(ACCENT_HEX))
LIGHT_GREY = colors.HexColor(css_hex(LIGHT_GREY_HEX))
MID_GREY   = colors.HexColor(css_hex(MID_GREY_HEX))
DARK_GREY  = colors.HexColor(css_hex(DARK_GREY_HEX))
ROW_ALT    = colors.HexColor(css_hex(ROW_ALT_HEX))
WHITE      = colors.white

BD_TZ  = timezone(timedelta(hours=6))
MARGIN = 18 * mm

STATIC_IMG_DIR = Path(__file__).resolve().parents[3] / "static" / "img"
LOGO_PATH = STATIC_IMG_DIR / "ConstructFlow-logo.png"
FOOTER_BOTTOM = 0
FOOTER_HEIGHT = 12 * mm
FOOTER_TOP = FOOTER_BOTTOM + FOOTER_HEIGHT
FOOTER_TEXT_Y = FOOTER_BOTTOM + 4 * mm
EDGE_FILL = 0.6 * mm


# ── Helpers ───────────────────────────────────────────────────────────────────
def _fmt(val):
    try:
        return format_money(val)
    except (TypeError, ValueError, InvalidOperation):
        return "TK 0.00"


def _pct(spent, budget):
    try:
        return percent_used(spent, budget)
    except (TypeError, ValueError, ZeroDivisionError, InvalidOperation):
        return ZERO


def S(name, **kw):
    return ParagraphStyle(name, **kw)


def _txt(value, fallback='\u2014'):
    return escape(str(value)) if value not in (None, '') else fallback


# ── Per-page header & footer ──────────────────────────────────────────────────
def _draw_header_footer(canvas, doc, print_date, is_cover=False):
    canvas.saveState()
    w, h = A4

    # ── Navy header bar ───────────────────────────────────────────────────
    canvas.setFillColor(NAVY)
    canvas.rect(0, h - 18*mm, w, 18*mm, fill=1, stroke=0)
    canvas.rect(w - EDGE_FILL, h - 18*mm, EDGE_FILL, 18*mm, fill=1, stroke=0)

    # Red accent line under header
    canvas.setFillColor(RED)
    canvas.rect(0, h - 19.5*mm, w, 1.5*mm, fill=1, stroke=0)
    canvas.rect(w - EDGE_FILL, h - 19.5*mm, EDGE_FILL, 1.5*mm, fill=1, stroke=0)

    # Logo
    logo_width = 14 * mm
    logo_height = 14 * mm

    if LOGO_PATH.exists():
        canvas.drawImage(
            str(LOGO_PATH),
            MARGIN,
            h - 15 * mm,
            width=logo_width,
            height=logo_height,
            preserveAspectRatio=True,
            mask='auto'
        )

    # Company name 
    text_x = MARGIN + 18 * mm
    canvas.setFont('Helvetica-Bold', 13)
    canvas.setFillColor(WHITE)
    canvas.drawString(
        text_x,
        h - 7.5 * mm,
        "ConstructFlow"
    )
    # Tagline below company name
    canvas.setFont('Helvetica-Oblique', 7)
    canvas.setFillColor(colors.HexColor(css_hex(TAGLINE_HEX)))
    canvas.drawString(text_x, h - 13*mm, "Construction Project Management System")

    # Date of print on the far right
    canvas.setFont('Helvetica', 8)
    canvas.setFillColor(WHITE)
    canvas.drawRightString(w - MARGIN, h - 8*mm, f"Date Generated:  {print_date}")

    # ── Footer ────────────────────────────────────────────────────────────
    canvas.setFillColor(colors.HexColor(css_hex(FOOTER_FILL_HEX)))
    canvas.setStrokeColor(colors.HexColor(css_hex(FOOTER_LINE_HEX)))
    canvas.setLineWidth(0.8)
    canvas.line(0, FOOTER_TOP, w, FOOTER_TOP)
    canvas.rect(0, FOOTER_BOTTOM, w, FOOTER_HEIGHT, fill=1, stroke=0)
    canvas.rect(w - EDGE_FILL, FOOTER_BOTTOM, EDGE_FILL, FOOTER_HEIGHT, fill=1, stroke=0)

    canvas.setFillColor(DARK_GREY)
    canvas.setFont('Helvetica-Oblique', 8)
    canvas.drawString(MARGIN, FOOTER_TEXT_Y, "ConstructFlow Report Generation Utility")

    canvas.setFont('Helvetica', 8)
    canvas.drawCentredString(w / 2, FOOTER_TEXT_Y, "Confidential | Internal Business Records")

    footer_right = "Generated by ConstructFlow ERP" if is_cover else f"Page {doc.page} | ConstructFlow"
    canvas.drawRightString(w - MARGIN, FOOTER_TEXT_Y, footer_right)

    canvas.restoreState()


# ── Main generator ────────────────────────────────────────────────────────────
def generate_costs_pdf(costs, project=None, cost_type_filter='',
                       start_date='', end_date='', include_ledger=True,
                       total_records=None, total_expenditure=None,
                       projects_covered=None, cost_type_summary=None,
                       generated_at=None) -> bytes:
    buffer     = BytesIO()
    print_date = (generated_at or datetime.now(BD_TZ)).strftime('%Y-%m-%d  %H:%M')
    is_single  = project is not None
    record_count = total_records if total_records is not None else len(costs)

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=MARGIN,
        rightMargin=MARGIN,
        topMargin=24*mm,
        bottomMargin=18*mm,
        title="ConstructFlow Expenditure Report",
        author="ConstructFlow",
    )

    cover_done = [False]
    def on_page(canvas, doc):
        _draw_header_footer(canvas, doc, print_date, is_cover=not cover_done[0])
        cover_done[0] = True

    normal = getSampleStyleSheet()['Normal']

    # ── Shared styles ──────────────────────────────────────────────────
    title_s = S(
        'RTitle',
        fontSize=26,
        leading=32,
        fontName='Helvetica-Bold',
        textColor=NAVY,
        alignment=TA_CENTER,
        spaceAfter=10
    )

    sub_s = S(
        'RSub',
        fontSize=11,
        leading=16,
        fontName='Helvetica',
        textColor=MID_GREY,
        alignment=TA_CENTER,
        spaceAfter=22
    )
    section_s = S('RSec',   fontSize=11, fontName='Helvetica-Bold',
                  textColor=NAVY, spaceBefore=8, spaceAfter=4)
    label_s   = S('RLbl',   fontSize=9,  fontName='Helvetica-Bold', textColor=DARK_GREY)
    value_s   = S('RVal',   fontSize=9,  fontName='Helvetica',      textColor=DARK_GREY)
    cell_s = S(
            'RCell',
            fontSize=7,
            leading=10,
            fontName='Helvetica',
            textColor=DARK_GREY
        )

    cell_r = S(
            'RCellR',
            fontSize=7,
            leading=10,
            fontName='Helvetica',
            textColor=DARK_GREY,
            alignment=TA_RIGHT
        )
    th_s = S(
            'RTH',
            fontSize=7,
            fontName='Helvetica-Bold',
            textColor=WHITE,
            alignment=TA_CENTER
        )
    notice_s  = S('RNote',  fontSize=7,  textColor=MID_GREY, alignment=TA_CENTER)

    story = []

    # ══════════════════════════════════════════════════════════════════════
    # COVER PAGE
    # ══════════════════════════════════════════════════════════════════════
    story.append(Spacer(1, 14*mm))

    # ── Title block ───────────────────────────────────────────────────────
    if is_single:
        story.append(Paragraph(_txt(project.project_name), title_s))
        story.append(Spacer(1, 4 * mm))
        story.append(Paragraph("Project Expenditure Report", sub_s))
    else:
        story.append(Paragraph("Expenditure Report", title_s))
        story.append(Spacer(1, 4 * mm))
        story.append(Paragraph("ConstructFlow \u2014 Multi-Project Cost Summary", sub_s))

    story.append(HRFlowable(width="100%", thickness=2, color=RED, spaceAfter=8))

    # ── Report Scope ──────────────────────────────────────────────────────
    story.append(Paragraph("Report Scope", section_s))

    scope_data = []

    if is_single:
        # All project fields the user entered
        scope_data += [
            [Paragraph("<b>Project Name</b>",   label_s), Paragraph(_txt(project.project_name),       value_s)],
            [Paragraph("<b>Sector</b>",          label_s), Paragraph(_txt(project.sector),             value_s)],
            [Paragraph("<b>Firm Name</b>",       label_s), Paragraph(_txt(project.firm_name),          value_s)],
            [Paragraph("<b>Tender ID</b>",       label_s), Paragraph(_txt(project.tender_id),          value_s)],
            [Paragraph("<b>Address</b>",         label_s), Paragraph(_txt(project.address),            value_s)],
            [Paragraph("<b>NOA Date</b>",        label_s), Paragraph(str(project.noa_date) if project.noa_date else '\u2014', value_s)],
            [Paragraph("<b>Work Order Year</b>", label_s), Paragraph(_txt(project.work_order_year),    value_s)],
            [Paragraph("<b>Project Status</b>",  label_s), Paragraph(_txt(project.status),             value_s)],
        ]
        if project.status == 'Completed':
            scope_data.append([
                Paragraph("<b>Completion Date</b>", label_s),
                Paragraph(str(project.completion_date) if project.completion_date else '\u2014', value_s),
            ])
        scope_data.append(
            [Paragraph("<b>Remarks</b>", label_s), Paragraph(_txt(project.additional_details), value_s)]
        )
    else:
        unique_projects = projects_covered if projects_covered is not None else len(set(c.project_id for c in costs))
        scope_data += [
            [Paragraph("<b>Report Type</b>",      label_s), Paragraph("Multi-Project Expenditure Report", value_s)],
            [Paragraph("<b>Projects Covered</b>", label_s), Paragraph(str(unique_projects),               value_s)],
        ]

    # Applied filters — always shown
    scope_data += [
        [Paragraph("<b>Category Filter</b>", label_s),
         Paragraph(_txt(cost_type_filter, "All Categories"), value_s)],
        [Paragraph("<b>Date From</b>",       label_s),
         Paragraph(_txt(start_date, "All Time"), value_s)],
        [Paragraph("<b>Date To</b>",         label_s),
         Paragraph(_txt(end_date, "All Time"),     value_s)],
        [Paragraph("<b>Total Records</b>",   label_s),
         Paragraph(str(record_count),                          value_s)],
    ]

    scope_table = Table(scope_data, colWidths=[45*mm, 125*mm])
    scope_table.setStyle(TableStyle([
        ('ROWBACKGROUNDS', (0, 0), (-1, -1), [WHITE, LIGHT_GREY]),
        ('GRID',           (0, 0), (-1, -1), 0.4, colors.HexColor(css_hex(SCOPE_GRID_HEX))),
        ('TOPPADDING',     (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING',  (0, 0), (-1, -1), 6),
        ('LEFTPADDING',    (0, 0), (-1, -1), 8),
        ('VALIGN',         (0, 0), (-1, -1), 'TOP'),
        ('LINEAFTER',      (0, 0), (0, -1),  0.8, NAVY),
    ]))
    story.append(scope_table)
    story.append(Spacer(1, 6*mm))

    # ── Financial Summary ─────────────────────────────────────────────────
    filtered_total = (
        to_money(total_expenditure)
        if total_expenditure is not None
        else sum((to_money(c.total_amount) for c in costs), ZERO)
    )

    if is_single:
        has_detail_filters = bool(cost_type_filter or start_date or end_date)

        if has_detail_filters:
            fin_data = [[
                Paragraph(
                    f"<font size='8' color='grey'>Filtered Records</font><br/>"
                    f"<b>{record_count}</b>", normal),
                Paragraph(
                    f"<font size='8' color='grey'>Filtered Expenditure</font><br/>"
                    f"<b><font color='{DARK_GREY_HEX}'>{_fmt(filtered_total)}</font></b>", normal),
            ]]
            fin_table = Table(fin_data, colWidths=[85*mm, 85*mm])
        else:
            budget = to_money(project.contract_price)
            remaining = budget - filtered_total
            percent = _pct(filtered_total, budget)
            rem_color = DARK_GREY_HEX if remaining >= 0 else ACCENT_HEX
            pct_color = DARK_GREY_HEX if percent < 80 else ACCENT_HEX

            fin_data = [[
                Paragraph(
                    f"<font size='8' color='grey'>Contract Price</font><br/>"
                    f"<b>{_fmt(budget)}</b>", normal),
                Paragraph(
                    f"<font size='8' color='grey'>Total Spent</font><br/>"
                    f"<b><font color='{DARK_GREY_HEX}'>{_fmt(filtered_total)}</font></b>", normal),
                Paragraph(
                    f"<font size='8' color='grey'>Budget Left</font><br/>"
                    f"<b><font color='{rem_color}'>{_fmt(remaining)}</font></b>", normal),
                Paragraph(
                    f"<font size='8' color='grey'>Budget Used</font><br/>"
                    f"<b><font color='{pct_color}'>{percent}%</font></b>", normal),
            ]]
            fin_table = Table(fin_data, colWidths=[42*mm, 42*mm, 42*mm, 42*mm])
    else:
        fin_data = [[
            Paragraph(
                f"<font size='8' color='grey'>Total Records</font><br/>"
                f"<b>{record_count}</b>", normal),
            Paragraph(
                f"<font size='8' color='grey'>Total Expenditure</font><br/>"
                f"<b><font color='{DARK_GREY_HEX}'>{_fmt(filtered_total)}</font></b>", normal),
        ]]
        fin_table = Table(fin_data, colWidths=[85*mm, 85*mm])

    fin_table.setStyle(TableStyle([
        ('BACKGROUND',    (0, 0), (-1, -1), LIGHT_GREY),
        ('GRID',          (0, 0), (-1, -1), 0.4, colors.HexColor(css_hex(BORDER_GREY_HEX))),
        ('ALIGN',         (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN',        (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING',    (0, 0), (-1, -1), 12),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
        ('BOX', (0,0), (-1,-1), 0.8, colors.HexColor(css_hex(BOX_GREY_HEX))),
    ]))
    story.append(KeepTogether([
        Paragraph("Financial Summary", section_s),
        HRFlowable(width="100%", thickness=0.5, color=NAVY, spaceAfter=5),
        fin_table,
    ]))
    story.append(Spacer(1, 7*mm))

    notice_text = (
        "This document is confidential and intended for internal use only. "
        "Unauthorised distribution is strictly prohibited."
    )
    notice_lines = [notice_text]
    if not include_ledger:
        notice_lines.append(
            "The itemized ledger is provided in the accompanying Excel workbook. "
            "Full PDF detail is not generated for very large reports."
        )
    notice_paragraphs = [Paragraph(line, notice_s) for line in notice_lines]

    if cost_type_summary:
        story.append(PageBreak())
        summary_rows = [[
            Paragraph("<b>Cost Type</b>", th_s),
            Paragraph("<b>Records</b>", th_s),
            Paragraph("<b>Total (TK)</b>", th_s),
        ]]
        for summary in cost_type_summary:
            summary_rows.append([
                Paragraph(_txt(summary.get('cost_type')), cell_s),
                Paragraph(str(summary.get('records', 0)), cell_r),
                Paragraph(_fmt(summary.get('total', 0)), cell_r),
            ])
        notice_start = len(summary_rows)
        for line in notice_lines:
            summary_rows.append([Paragraph(line, notice_s), Paragraph("", notice_s), Paragraph("", notice_s)])
        summary_table = Table(summary_rows, colWidths=[90*mm, 30*mm, 50*mm], repeatRows=1)
        summary_style = [
            ('BACKGROUND', (0, 0), (-1, 0), NAVY),
            ('TEXTCOLOR', (0, 0), (-1, 0), WHITE),
            ('LINEBELOW', (0, 0), (-1, 0), 1, RED),
            ('ROWBACKGROUNDS', (0, 1), (-1, notice_start - 1), [WHITE, ROW_ALT]),
            ('GRID', (0, 0), (-1, notice_start - 1), 0.4, colors.HexColor(css_hex(BORDER_GREY_HEX))),
            ('ALIGN', (1, 1), (-1, notice_start - 1), 'RIGHT'),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('TOPPADDING', (0, 0), (-1, notice_start - 1), 4),
            ('BOTTOMPADDING', (0, 0), (-1, notice_start - 1), 4),
            ('BACKGROUND', (0, notice_start), (-1, -1), WHITE),
            ('ALIGN', (0, notice_start), (-1, -1), 'CENTER'),
            ('TOPPADDING', (0, notice_start), (-1, notice_start), 7),
            ('BOTTOMPADDING', (0, notice_start), (-1, -1), 2),
        ]
        for row_index in range(notice_start, len(summary_rows)):
            summary_style.append(('SPAN', (0, row_index), (-1, row_index)))
        if notice_start > 1:
            summary_style.append(('NOSPLIT', (0, notice_start - 1), (-1, len(summary_rows) - 1)))
        summary_table.setStyle(TableStyle(summary_style))
        story.extend([
            Paragraph("Cost-Type Summary", section_s),
            HRFlowable(width="100%", thickness=0.5, color=NAVY, spaceAfter=5),
            summary_table,
        ])
        story.append(Spacer(1, 7*mm))
    else:
        story.extend(notice_paragraphs)
        story.append(Spacer(1, 7*mm))

    if not include_ledger:
        doc.build(story, onFirstPage=on_page, onLaterPages=on_page)
        buffer.seek(0)
        return buffer.read()

    # ══════════════════════════════════════════════════════════════════════
    # PAGE 2+: ITEMIZED LEDGER
    # ══════════════════════════════════════════════════════════════════════
    story.append(PageBreak())
    story.append(Paragraph("Itemized Cost Ledger", section_s))
    story.append(HRFlowable(width="100%", thickness=0.5, color=NAVY, spaceAfter=6))

    if is_single:
        col_widths = [7*mm, 18*mm, 24*mm, 14*mm, 18*mm, 22*mm, 58*mm]
        headers    = ["SL", "Date", "Cost Type", "Qty", "Unit Rate", "Total (TK)", "Remarks"]
    else:
        col_widths = [7*mm, 16*mm, 30*mm, 18*mm, 12*mm, 16*mm, 18*mm, 45*mm]
        headers    = ["SL", "Date", "Project", "Cost Type", "Qty", "Unit Rate", "Total (TK)", "Remarks"]

    rows = [[Paragraph(f"<b>{h}</b>", th_s) for h in headers]]

    for i, c in enumerate(costs, start=1):
        date_str  = str(c.date) if c.date else '\u2014'
        cost_t    = _txt(c.cost_type)
        qty_s     = format_money(c.quantity or 0, prefix="")
        rate_s    = _fmt(c.unit_rate or 0)
        total_s   = _fmt(c.total_amount or 0)
        rem_s = _txt(c.remarks[:40] + "..." if c.remarks and len(c.remarks) > 40 else c.remarks)
        proj_s    = _txt(c.project.project_name if c.project else None)
        amount_color = ACCENT_HEX if to_money(c.total_amount) < 0 else DARK_GREY_HEX

        if is_single:
            rows.append([
                Paragraph(str(i),   cell_s),
                Paragraph(date_str, cell_s),
                Paragraph(cost_t,   cell_s),
                Paragraph(qty_s,    cell_r),
                Paragraph(rate_s,   cell_r),
                Paragraph(
                        f"<font color='{amount_color}'>{total_s}</font>",
                        cell_r
                    ),
                Paragraph(rem_s,    cell_s),
            ])
        else:
            rows.append([
                Paragraph(str(i),   cell_s),
                Paragraph(date_str, cell_s),
                Paragraph(proj_s,   cell_s),
                Paragraph(cost_t,   cell_s),
                Paragraph(qty_s,    cell_r),
                Paragraph(rate_s,   cell_r),
                Paragraph(
                        f"<font color='{amount_color}'>{total_s}</font>",
                        cell_r
                    ),
                Paragraph(rem_s,    cell_s),
            ])

    # Grand total row
    n_cols = len(headers)
    n_rows = len(rows) + 1
    total_row = (
        [Paragraph('', cell_s)] * (n_cols - 2) + [
            Paragraph("<b>Grand Total</b>",
                      S('GT',  fontSize=8, fontName='Helvetica-Bold', alignment=TA_RIGHT)),
            Paragraph(f"<b>{_fmt(filtered_total)}</b>",
                      S('GTV', fontSize=8, fontName='Helvetica-Bold',
                        textColor=DARK_GREY, alignment=TA_RIGHT)),
        ]
    )
    rows.append(total_row)

    ledger = Table(rows, colWidths=col_widths, repeatRows=1)
    ledger.setStyle(TableStyle([
        ('BACKGROUND',     (0, 0),        (-1, 0),        NAVY),
        ('TEXTCOLOR',      (0, 0),        (-1, 0),        WHITE),
        ('ALIGN',          (0, 0),        (-1, 0),        'CENTER'),
        ('ROWBACKGROUNDS', (0, 1),        (-1, n_rows-2), [WHITE, ROW_ALT]),
        ('BACKGROUND',     (0, n_rows-1), (-1, n_rows-1), colors.HexColor(css_hex(TOTAL_FILL_HEX))),
        ('SPAN',           (0, n_rows-1), (n_cols-3,      n_rows-1)),
        ('GRID',           (0, 0),        (-1, -1),       0.4, colors.HexColor(css_hex(BORDER_GREY_HEX))),
        ('LINEBELOW',      (0, 0),        (-1, 0),        1,   RED),
        ('VALIGN',         (0, 0),        (-1, -1),       'TOP'),
        ('TOPPADDING',     (0, 0),        (-1, -1),       2),
        ('BOTTOMPADDING',  (0, 0),        (-1, -1),       2),
        ('LEFTPADDING',    (0, 0),        (-1, -1),       4),
        ('RIGHTPADDING',   (0, 0),        (-1, -1),       4),
        ('LINEBEFORE', (5,1), (5,-1), 0.4, colors.HexColor(css_hex(LEDGER_DIVIDER_HEX))),
    ]))
    story.append(ledger)
    story.append(Spacer(1, 3 * mm))

    story.append(
        Paragraph(
            f"<font color='{DARK_GREY_HEX}'><b>Accounting Note:</b></font> "
            "Negative expenditure values represent refunds, reversals, supplier returns, or financial adjustments.",
            notice_s
        )
)

    doc.build(story, onFirstPage=on_page, onLaterPages=on_page)
    buffer.seek(0)
    return buffer.read()
