from io import BytesIO

from openpyxl import Workbook
from openpyxl.cell import WriteOnlyCell
from openpyxl.styles import Alignment, Font, PatternFill, Border, Side
from openpyxl.utils import get_column_letter

from app.modules.construction.utils.money import to_money, ZERO
from app.modules.construction.utils.report_palette import (
    ACCENT_HEX,
    BORDER_GREY_HEX,
    DARK_GREY_HEX,
    INK_HEX,
    ROW_ALT_HEX,
    TOTAL_FILL_HEX,
    WHITE_HEX,
)


MONEY_FORMAT = '#,##0.00;[Red]-#,##0.00'


def _cell(ws, value, font=None, fill=None, border=None, alignment=None, number_format=None):
    cell = WriteOnlyCell(ws, value=value)
    if font:
        cell.font = font
    if fill:
        cell.fill = fill
    if border:
        cell.border = border
    if alignment:
        cell.alignment = alignment
    if number_format:
        cell.number_format = number_format
    return cell


def _project_name(row):
    if hasattr(row, "project_name"):
        return row.project_name
    project = getattr(row, "project", None)
    return project.project_name if project else ""


def generate_costs_excel(rows, project=None, cost_type_filter="", start_date="", end_date="", generated_at=None) -> bytes:
    wb = Workbook(write_only=True)
    ws = wb.create_sheet("Cost Ledger")
    is_single_project = project is not None
    generated_text = generated_at.strftime("%Y-%m-%d  %H:%M") if generated_at else ""

    ws.freeze_panes = "A7"
    ws.print_title_rows = "6:6"
    ws.sheet_view.showGridLines = False
    ws.page_setup.orientation = "landscape"
    ws.page_setup.fitToWidth = 1
    ws.page_setup.fitToHeight = 0
    ws.sheet_properties.pageSetUpPr.fitToPage = True
    ws.page_margins.left = 0.25
    ws.page_margins.right = 0.25
    ws.page_margins.top = 0.5
    ws.page_margins.bottom = 0.5
    for header in (ws.oddHeader, ws.evenHeader, ws.firstHeader):
        header.center.text = "ConstructFlow - Cost Ledger"
        header.right.text = f"Date Generated: {generated_text}" if generated_text else ""
    for footer in (ws.oddFooter, ws.evenFooter, ws.firstFooter):
        footer.left.text = "Confidential | Internal Business Records"
        footer.center.text = "Generated by ConstructFlow ERP"
        footer.right.text = "Page &P of &N"

    widths = [8, 14, 22, 14, 16, 18, 48] if is_single_project else [8, 14, 34, 22, 14, 16, 18, 48]
    for index, width in enumerate(widths, start=1):
        ws.column_dimensions[get_column_letter(index)].width = width

    title_font = Font(bold=True, color=INK_HEX, size=16)
    meta_font = Font(color=DARK_GREY_HEX, size=10)
    header_font = Font(bold=True, color=WHITE_HEX)
    header_fill = PatternFill("solid", fgColor=INK_HEX)
    total_fill = PatternFill("solid", fgColor=TOTAL_FILL_HEX)
    thin = Side(style="thin", color=BORDER_GREY_HEX)
    border = Border(top=thin, bottom=thin, left=thin, right=thin)
    left = Alignment(horizontal="left", vertical="top", wrap_text=True)
    center = Alignment(horizontal="center", vertical="top")
    right = Alignment(horizontal="right", vertical="top")

    scope = project.project_name if project else "All Running Projects"
    filters = (
        f"Project: {scope} | Category: {cost_type_filter or 'All Categories'} | "
        f"Date From: {start_date or 'All Time'} | Date To: {end_date or 'All Time'}"
    )
    generated_label = f"Date Generated: {generated_text}" if generated_text else ""
    sort_label = "Sort Order: Date ascending, then Entry ID ascending"
    ws.append([_cell(ws, "ConstructFlow", font=title_font)])
    ws.append([_cell(ws, "Printable Cost Ledger", font=Font(bold=True, color=ACCENT_HEX, size=12))])
    ws.append([_cell(ws, filters, font=meta_font)])
    ws.append([_cell(ws, generated_label, font=meta_font)])
    ws.append([_cell(ws, sort_label, font=meta_font)])

    headers = ["SL", "Date", "Cost Type", "Quantity", "Unit Rate", "Total Amount", "Remarks"]
    if not is_single_project:
        headers.insert(2, "Project")
    last_col = get_column_letter(len(headers))
    ws.auto_filter.ref = f"A6:{last_col}6"
    ws.append([
        _cell(ws, header, font=header_font, fill=header_fill, border=border, alignment=center)
        for header in headers
    ])

    grand_total = ZERO
    row_count = 0
    body_fill = PatternFill("solid", fgColor=ROW_ALT_HEX)
    for row_count, cost in enumerate(rows, start=1):
        amount = to_money(cost.total_amount or 0)
        grand_total += amount
        fill = body_fill if row_count % 2 == 0 else None
        row_cells = [
            _cell(ws, row_count, fill=fill, border=border, alignment=center),
            _cell(ws, cost.date, fill=fill, border=border, alignment=center, number_format="yyyy-mm-dd"),
            _cell(ws, cost.cost_type, fill=fill, border=border, alignment=left),
            _cell(ws, float(to_money(cost.quantity or 0)), fill=fill, border=border, alignment=right, number_format=MONEY_FORMAT),
            _cell(ws, float(to_money(cost.unit_rate or 0)), fill=fill, border=border, alignment=right, number_format=MONEY_FORMAT),
            _cell(ws, float(amount), fill=fill, border=border, alignment=right, number_format=MONEY_FORMAT),
            _cell(ws, cost.remarks or "", fill=fill, border=border, alignment=left),
        ]
        if not is_single_project:
            row_cells.insert(2, _cell(ws, _project_name(cost), fill=fill, border=border, alignment=left))
        ws.append(row_cells)

    total_prefix_cells = len(headers) - 3
    ws.append(
        [_cell(ws, "", fill=total_fill, border=border) for _ in range(total_prefix_cells)] + [
        _cell(ws, "Grand Total", font=Font(bold=True), fill=total_fill, border=border, alignment=right),
        _cell(ws, float(grand_total), font=Font(bold=True, color=DARK_GREY_HEX), fill=total_fill, border=border, alignment=right, number_format=MONEY_FORMAT),
        _cell(ws, f"{row_count:,} rows", font=Font(bold=True), fill=total_fill, border=border, alignment=left),
    ])

    output = BytesIO()
    wb.save(output)
    output.seek(0)
    return output.read()
