
from io import BytesIO
from datetime import datetime, timezone, timedelta
from pathlib import Path
from xml.sax.saxutils import escape

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, KeepTogether, PageBreak
)

# ── Brand colours ─────────────────────────────────────────────────────────────
NAVY       = colors.HexColor('#1a2a6c')
RED        = colors.HexColor('#e63946')
LIGHT_GREY = colors.HexColor('#f4f6f9')
MID_GREY   = colors.HexColor('#7a7a7a')
DARK_GREY  = colors.HexColor('#333333')
ROW_ALT    = colors.HexColor('#eef1f8')
WHITE      = colors.white
GREEN      = colors.HexColor('#2e7d32')
AMBER      = colors.HexColor('#e65100')

BD_TZ  = timezone(timedelta(hours=6))
MARGIN = 18 * mm

STATIC_IMG_DIR = Path(__file__).resolve().parents[3] / "static" / "img"
LOGO_PATH = STATIC_IMG_DIR / "ConstructFlow-logo.png"
FOOTER_BOTTOM = 0
FOOTER_HEIGHT = 12 * mm
FOOTER_TOP = FOOTER_BOTTOM + FOOTER_HEIGHT
FOOTER_TEXT_Y = FOOTER_BOTTOM + 4 * mm
EDGE_FILL = 0.6 * mm


# ── Helpers ───────────────────────────────────────────────────────────────────
def _fmt(val):
    try:
        return f"TK {float(val):,.2f}"
    except (TypeError, ValueError):
        return "TK 0.00"


def _pct(spent, budget):
    try:
        return round(float(spent) / float(budget) * 100, 1) if float(budget) > 0 else 0.0
    except (TypeError, ValueError, ZeroDivisionError):
        return 0.0


def S(name, **kw):
    return ParagraphStyle(name, **kw)


def _txt(value, fallback='\u2014'):
    return escape(str(value)) if value not in (None, '') else fallback


# ── Per-page header & footer ──────────────────────────────────────────────────
def _draw_header_footer(canvas, doc, print_date, is_cover=False):
    canvas.saveState()
    w, h = A4

    # ── Navy header bar ───────────────────────────────────────────────────
    canvas.setFillColor(NAVY)
    canvas.rect(0, h - 18*mm, w, 18*mm, fill=1, stroke=0)
    canvas.rect(w - EDGE_FILL, h - 18*mm, EDGE_FILL, 18*mm, fill=1, stroke=0)

    # Red accent line under header
    canvas.setFillColor(RED)
    canvas.rect(0, h - 19.5*mm, w, 1.5*mm, fill=1, stroke=0)
    canvas.rect(w - EDGE_FILL, h - 19.5*mm, EDGE_FILL, 1.5*mm, fill=1, stroke=0)

    # Logo
    logo_width = 14 * mm
    logo_height = 14 * mm

    if LOGO_PATH.exists():
        canvas.drawImage(
            str(LOGO_PATH),
            MARGIN,
            h - 15 * mm,
            width=logo_width,
            height=logo_height,
            preserveAspectRatio=True,
            mask='auto'
        )

    # Company name 
    text_x = MARGIN + 18 * mm
    canvas.setFont('Helvetica-Bold', 13)
    canvas.setFillColor(WHITE)
    canvas.drawString(
        text_x,
        h - 7.5 * mm,
        "ConstructFlow"
    )
    # Tagline below company name
    canvas.setFont('Helvetica-Oblique', 7)
    canvas.setFillColor(colors.HexColor('#c7d2f0'))
    canvas.drawString(text_x, h - 13*mm, "Construction Project Cost Management")

    # Date of print on the far right
    canvas.setFont('Helvetica', 8)
    canvas.setFillColor(WHITE)
    canvas.drawRightString(w - MARGIN, h - 8*mm, f"Date of Print:  {print_date}")

    # ── Footer ────────────────────────────────────────────────────────────
    canvas.setFillColor(colors.HexColor('#eef1f8'))
    canvas.setStrokeColor(colors.HexColor('#c9d2e6'))
    canvas.setLineWidth(0.8)
    canvas.line(0, FOOTER_TOP, w, FOOTER_TOP)
    canvas.rect(0, FOOTER_BOTTOM, w, FOOTER_HEIGHT, fill=1, stroke=0)
    canvas.rect(w - EDGE_FILL, FOOTER_BOTTOM, EDGE_FILL, FOOTER_HEIGHT, fill=1, stroke=0)

    canvas.setFillColor(DARK_GREY)
    canvas.setFont('Helvetica-Oblique', 8)
    canvas.drawString(MARGIN, FOOTER_TEXT_Y, "ConstructFlow Report Generation Utility")

    canvas.setFont('Helvetica', 8)
    canvas.drawCentredString(w / 2, FOOTER_TEXT_Y, "Confidential | Internal Business Records")

    footer_right = "Generated by ConstructFlow ERP" if is_cover else f"Page {doc.page} | ConstructFlow"
    canvas.drawRightString(w - MARGIN, FOOTER_TEXT_Y, footer_right)

    canvas.restoreState()


# ── Main generator ────────────────────────────────────────────────────────────
def generate_costs_pdf(costs, project=None, cost_type_filter='',
                       start_date='', end_date='') -> bytes:
    buffer     = BytesIO()
    print_date = datetime.now(BD_TZ).strftime('%Y-%m-%d  %H:%M')
    is_single  = project is not None

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=MARGIN,
        rightMargin=MARGIN,
        topMargin=24*mm,
        bottomMargin=18*mm,
        title="ConstructFlow Expenditure Report",
        author="ConstructFlow",
    )

    cover_done = [False]
    def on_page(canvas, doc):
        _draw_header_footer(canvas, doc, print_date, is_cover=not cover_done[0])
        cover_done[0] = True

    normal = getSampleStyleSheet()['Normal']

    # ── Shared styles ──────────────────────────────────────────────────
    title_s = S(
        'RTitle',
        fontSize=26,
        leading=32,
        fontName='Helvetica-Bold',
        textColor=NAVY,
        alignment=TA_CENTER,
        spaceAfter=10
    )

    sub_s = S(
        'RSub',
        fontSize=11,
        leading=16,
        fontName='Helvetica',
        textColor=MID_GREY,
        alignment=TA_CENTER,
        spaceAfter=22
    )
    section_s = S('RSec',   fontSize=11, fontName='Helvetica-Bold',
                  textColor=NAVY, spaceBefore=8, spaceAfter=4)
    label_s   = S('RLbl',   fontSize=9,  fontName='Helvetica-Bold', textColor=DARK_GREY)
    value_s   = S('RVal',   fontSize=9,  fontName='Helvetica',      textColor=DARK_GREY)
    cell_s = S(
            'RCell',
            fontSize=7,
            leading=10,
            fontName='Helvetica',
            textColor=DARK_GREY
        )

    cell_r = S(
            'RCellR',
            fontSize=7,
            leading=10,
            fontName='Helvetica',
            textColor=DARK_GREY,
            alignment=TA_RIGHT
        )
    th_s = S(
            'RTH',
            fontSize=7,
            fontName='Helvetica-Bold',
            textColor=WHITE,
            alignment=TA_CENTER
        )
    notice_s  = S('RNote',  fontSize=7,  textColor=MID_GREY, alignment=TA_CENTER)

    story = []

    # ══════════════════════════════════════════════════════════════════════
    # COVER PAGE
    # ══════════════════════════════════════════════════════════════════════
    story.append(Spacer(1, 14*mm))

    # ── Title block ───────────────────────────────────────────────────────
    if is_single:
        story.append(Paragraph(_txt(project.project_name), title_s))
        story.append(Spacer(1, 4 * mm))
        story.append(Paragraph("Project Expenditure Report", sub_s))
    else:
        story.append(Paragraph("Expenditure Report", title_s))
        story.append(Spacer(1, 4 * mm))
        story.append(Paragraph("ConstructFlow \u2014 Multi-Project Cost Summary", sub_s))

    story.append(HRFlowable(width="100%", thickness=2, color=RED, spaceAfter=8))

    # ── Report Scope ──────────────────────────────────────────────────────
    story.append(Paragraph("Report Scope", section_s))

    scope_data = []

    if is_single:
        # All project fields the user entered
        scope_data += [
            [Paragraph("<b>Project Name</b>",   label_s), Paragraph(_txt(project.project_name),       value_s)],
            [Paragraph("<b>Sector</b>",          label_s), Paragraph(_txt(project.sector),             value_s)],
            [Paragraph("<b>Firm Name</b>",       label_s), Paragraph(_txt(project.firm_name),          value_s)],
            [Paragraph("<b>Tender ID</b>",       label_s), Paragraph(_txt(project.tender_id),          value_s)],
            [Paragraph("<b>Address</b>",         label_s), Paragraph(_txt(project.address),            value_s)],
            [Paragraph("<b>NOA Date</b>",        label_s), Paragraph(str(project.noa_date) if project.noa_date else '\u2014', value_s)],
            [Paragraph("<b>Work Order Year</b>", label_s), Paragraph(_txt(project.work_order_year),    value_s)],
            [Paragraph("<b>Project Status</b>",  label_s), Paragraph(_txt(project.status),             value_s)],
            [Paragraph("<b>Remarks</b>",         label_s), Paragraph(_txt(project.additional_details), value_s)],
        ]
    else:
        unique_projects = len(set(c.project_id for c in costs))
        scope_data += [
            [Paragraph("<b>Report Type</b>",      label_s), Paragraph("Multi-Project Expenditure Report", value_s)],
            [Paragraph("<b>Projects Covered</b>", label_s), Paragraph(str(unique_projects),               value_s)],
        ]

    # Applied filters — always shown
    scope_data += [
        [Paragraph("<b>Category Filter</b>", label_s),
         Paragraph(_txt(cost_type_filter, "All Categories"), value_s)],
        [Paragraph("<b>Date From</b>",       label_s),
         Paragraph(_txt(start_date, "All Time"), value_s)],
        [Paragraph("<b>Date To</b>",         label_s),
         Paragraph(_txt(end_date, "All Time"),     value_s)],
        [Paragraph("<b>Total Records</b>",   label_s),
         Paragraph(str(len(costs)),                          value_s)],
    ]

    scope_table = Table(scope_data, colWidths=[45*mm, 125*mm])
    scope_table.setStyle(TableStyle([
        ('ROWBACKGROUNDS', (0, 0), (-1, -1), [WHITE, LIGHT_GREY]),
        ('GRID',           (0, 0), (-1, -1), 0.4, colors.HexColor('#dde3ee')),
        ('TOPPADDING',     (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING',  (0, 0), (-1, -1), 6),
        ('LEFTPADDING',    (0, 0), (-1, -1), 8),
        ('VALIGN',         (0, 0), (-1, -1), 'TOP'),
        ('LINEAFTER',      (0, 0), (0, -1),  0.8, NAVY),
    ]))
    story.append(scope_table)
    story.append(Spacer(1, 6*mm))

    # ── Financial Summary ─────────────────────────────────────────────────
    total_spent = sum(float(c.total_amount or 0) for c in costs)

    if is_single:
        budget    = float(project.contract_price or 0)
        remaining = budget - total_spent
        percent   = _pct(total_spent, budget)

        rem_color = '#2e7d32' if remaining >= 0 else '#e63946'
        pct_color = '#2e7d32' if percent < 80 else ('#e65100' if percent < 100 else '#e63946')

        fin_data = [[
            Paragraph(
                f"<font size='8' color='grey'>Contract Price</font><br/>"
                f"<b>{_fmt(budget)}</b>", normal),
            Paragraph(
                f"<font size='8' color='grey'>Total Spent</font><br/>"
                f"<b><font color='#e63946'>{_fmt(total_spent)}</font></b>", normal),
            Paragraph(
                f"<font size='8' color='grey'>Remaining</font><br/>"
                f"<b><font color='{rem_color}'>{_fmt(remaining)}</font></b>", normal),
            Paragraph(
                f"<font size='8' color='grey'>Budget Used</font><br/>"
                f"<b><font color='{pct_color}'>{percent}%</font></b>", normal),
        ]]
        fin_table = Table(fin_data, colWidths=[42*mm, 42*mm, 42*mm, 42*mm])
    else:
        fin_data = [[
            Paragraph(
                f"<font size='8' color='grey'>Total Records</font><br/>"
                f"<b>{len(costs)}</b>", normal),
            Paragraph(
                f"<font size='8' color='grey'>Total Expenditure</font><br/>"
                f"<b><font color='#e63946'>{_fmt(total_spent)}</font></b>", normal),
        ]]
        fin_table = Table(fin_data, colWidths=[85*mm, 85*mm])

    fin_table.setStyle(TableStyle([
        ('BACKGROUND',    (0, 0), (-1, -1), LIGHT_GREY),
        ('GRID',          (0, 0), (-1, -1), 0.4, colors.HexColor('#cdd3e0')),
        ('ALIGN',         (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN',        (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING',    (0, 0), (-1, -1), 12),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
        ('BOX', (0,0), (-1,-1), 0.8, colors.HexColor('#d7ddea')),
    ]))
    story.append(KeepTogether([
        Paragraph("Financial Summary", section_s),
        HRFlowable(width="100%", thickness=0.5, color=NAVY, spaceAfter=5),
        fin_table,
    ]))
    story.append(Spacer(1, 7*mm))

    # Confidential notice
    story.append(HRFlowable(width="100%", thickness=0.5,
                             color=colors.HexColor('#cccccc'), spaceAfter=4))
    story.append(Paragraph(
        "This document is confidential and intended for internal use only. "
        "Unauthorised distribution is strictly prohibited.",
        notice_s
    ))

    # ══════════════════════════════════════════════════════════════════════
    # PAGE 2+: ITEMIZED LEDGER
    # ══════════════════════════════════════════════════════════════════════
    story.append(PageBreak())
    story.append(Paragraph("Itemized Cost Ledger", section_s))
    story.append(HRFlowable(width="100%", thickness=0.5, color=NAVY, spaceAfter=6))

    if is_single:
        col_widths = [7*mm, 18*mm, 24*mm, 14*mm, 18*mm, 22*mm, 58*mm]
        headers    = ["ID", "Date", "Cost Type", "Qty", "Unit Rate", "Total (TK)", "Remarks"]
    else:
        col_widths = [7*mm, 16*mm, 30*mm, 18*mm, 12*mm, 16*mm, 18*mm, 45*mm]
        headers    = ["ID", "Date", "Project", "Cost Type", "Qty", "Unit Rate", "Total (TK)", "Remarks"]

    rows = [[Paragraph(f"<b>{h}</b>", th_s) for h in headers]]

    for i, c in enumerate(costs, start=1):
        date_str  = str(c.date) if c.date else '\u2014'
        cost_t    = _txt(c.cost_type)
        qty_s     = f"{float(c.quantity or 0):,.2f}"
        rate_s    = _fmt(c.unit_rate or 0)
        total_s   = _fmt(c.total_amount or 0)
        rem_s = _txt(c.remarks[:40] + "..." if c.remarks and len(c.remarks) > 40 else c.remarks)
        proj_s    = _txt(c.project.project_name if c.project else None)
        amount_color = '#e63946' if float(c.total_amount or 0) < 0 else DARK_GREY

        if is_single:
            rows.append([
                Paragraph(str(i),   cell_s),
                Paragraph(date_str, cell_s),
                Paragraph(cost_t,   cell_s),
                Paragraph(qty_s,    cell_r),
                Paragraph(rate_s,   cell_r),
                Paragraph(
                        f"<font color='{amount_color}'>{total_s}</font>",
                        cell_r
                    ),
                Paragraph(rem_s,    cell_s),
            ])
        else:
            rows.append([
                Paragraph(str(i),   cell_s),
                Paragraph(date_str, cell_s),
                Paragraph(proj_s,   cell_s),
                Paragraph(cost_t,   cell_s),
                Paragraph(qty_s,    cell_r),
                Paragraph(rate_s,   cell_r),
                Paragraph(
                        f"<font color='{amount_color}'>{total_s}</font>",
                        cell_r
                    ),
                Paragraph(rem_s,    cell_s),
            ])

    # Grand total row
    n_cols = len(headers)
    n_rows = len(rows) + 1
    total_row = (
        [Paragraph('', cell_s)] * (n_cols - 2) + [
            Paragraph("<b>Grand Total</b>",
                      S('GT',  fontSize=8, fontName='Helvetica-Bold', alignment=TA_RIGHT)),
            Paragraph(f"<b>{_fmt(total_spent)}</b>",
                      S('GTV', fontSize=8, fontName='Helvetica-Bold',
                        textColor=RED, alignment=TA_RIGHT)),
        ]
    )
    rows.append(total_row)

    ledger = Table(rows, colWidths=col_widths, repeatRows=1)
    ledger.setStyle(TableStyle([
        ('BACKGROUND',     (0, 0),        (-1, 0),        NAVY),
        ('TEXTCOLOR',      (0, 0),        (-1, 0),        WHITE),
        ('ALIGN',          (0, 0),        (-1, 0),        'CENTER'),
        ('ROWBACKGROUNDS', (0, 1),        (-1, n_rows-2), [WHITE, ROW_ALT]),
        ('BACKGROUND',     (0, n_rows-1), (-1, n_rows-1), colors.HexColor('#dde3f5')),
        ('SPAN',           (0, n_rows-1), (n_cols-3,      n_rows-1)),
        ('GRID',           (0, 0),        (-1, -1),       0.4, colors.HexColor('#d0d6e8')),
        ('LINEBELOW',      (0, 0),        (-1, 0),        1,   RED),
        ('VALIGN',         (0, 0),        (-1, -1),       'TOP'),
        ('TOPPADDING',     (0, 0),        (-1, -1),       2),
        ('BOTTOMPADDING',  (0, 0),        (-1, -1),       2),
        ('LEFTPADDING',    (0, 0),        (-1, -1),       4),
        ('RIGHTPADDING',   (0, 0),        (-1, -1),       4),
        ('LINEBEFORE', (5,1), (5,-1), 0.4, colors.HexColor('#d6dceb')),
    ]))
    story.append(ledger)
    story.append(Spacer(1, 3 * mm))

    story.append(
        Paragraph(
            "<font color='#2e7d32'><b>Accounting Note:</b></font> "
            "Negative expenditure values represent refunds, reversals, supplier returns, or financial adjustments.",
            notice_s
        )
)

    doc.build(story, onFirstPage=on_page, onLaterPages=on_page)
    buffer.seek(0)
    return buffer.read()
