INK_HEX = '203864'
ACCENT_HEX = '9A3B3F'
LIGHT_GREY_HEX = 'F3F6FA'
MID_GREY_HEX = '667085'
DARK_GREY_HEX = '333333'
ROW_ALT_HEX = 'EDF2F7'
TOTAL_FILL_HEX = 'DDE6F2'
BORDER_GREY_HEX = 'CFD8E3'
BOX_GREY_HEX = 'D7DFEA'
TAGLINE_HEX = 'D8E0EE'
FOOTER_FILL_HEX = 'EEF3F8'
FOOTER_LINE_HEX = 'C9D3DF'
SCOPE_GRID_HEX = 'D5DCE6'
LEDGER_DIVIDER_HEX = 'D4DCE7'
WHITE_HEX = 'FFFFFF'


def css_hex(value):
    return f'#{value}'
